color: green
notes:
  - ~/dev/sandvik/tobias-ericsson/notes
  - /Users/tibbe/dev/me/powdrsoft.gitlab.io/hugo/content/notes
  - https://notes.tibbes.com/notes
  - ~/dev/me/powdrsoft.gitlab.io/hugo/content/notes
  - /Users/tibbe/dev/me/notes/notes
