version: '3'

tasks:
  dotfiles:setup:
    status:
      - test -L ~/.gitconfig
      - test -L ~/.uh.yaml
      - test -L ~/.vimrc

    cmds:
      - ./dotfiles-setup.sh

  brew:install:
    cmds:
      - ./brew/brew-install.sh

  karabiner:setup:
    status:
      # check if symlink exists
      - test -L ~/.config/karabiner/assets/complex_modifications 
    cmds:
      - ./karabiner/setup.sh    

  zsh:setup:
    deps: [brew:install]
    status:
      # check if .zshrc is symlink 
      - test -L ~/.zshrc
    cmds:
      - rm ~/.zshrc
      - ln -s ~/dev/me/dotfiles/zsh/zshrc ~/.zshrc
      - source ~/.zshrc

  git:setup:
    deps: [brew:install]
    status:
    cmds:
      - ./git/gitrepos.sh

  git:push:
    preconditions:
      # test existence of modified files, grep will exit with a failure if there is no match
      - sh: git ls-files -m -o | grep -E '.'
        msg: "nothing to do, no modified files"
    #status:
    #  - git status
    cmds:
      - git add --all
      - git commit -m "config"
      - git push

