# uncomment to profile startup time
# zmodload zsh/zprof
# Performance optimizations
DISABLE_AUTO_UPDATE="true"
DISABLE_MAGIC_FUNCTIONS="true"
DISABLE_COMPFIX="true"

# Cache completions aggressively
autoload -Uz compinit
if [ "$(date +'%j')" != "$(stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)" ]; then
    compinit
else
    compinit -C
fi

ZSH=$HOME/.oh-my-zsh

ZSH_CUSTOM=$HOME/dev/me/dotfiles/zsh/custom

ZSH_THEME="arrow"

plugins=(
        git 
        direnv
        zsh-autosuggestions
        zsh-history-substring-search
        zsh-syntax-highlighting
)

source <(fzf --zsh)
source $ZSH/oh-my-zsh.sh

eval $(thefuck --alias)

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/tobias/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/tobias/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/tobias/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/tobias/Downloads/google-cloud-sdk/completion.zsh.inc'; fi

# not included due to slow loading times
# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Added by Windsurf
export PATH="/Users/tobias/.codeium/windsurf/bin:$PATH"

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/tobias/.lmstudio/bin"

# THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# uncomment to profile startup time
# zprof

test -e /Users/tobias/.iterm2_shell_integration.zsh && source /Users/tobias/.iterm2_shell_integration.zsh || true
